"use client"

import React, { useEffect } from 'react';
import initializeAOS from '../utils/aos';

import 'bootstrap/dist/css/bootstrap.css';


import './globals.css'
import Menubar from './components/Menubar';


import { Mulish  } from 'next/font/google'
import Footer from './components/Footer';
import Topbar from './components/Topbar';


// const mulish = Mulish({ subsets: ['latin'] })
const mulish = Mulish({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap'
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  useEffect(() => {
    initializeAOS();
  }, []);

  return (
    <html lang="en">
      <body className={mulish.className}>
        <Topbar />
        <Menubar />
          {children}
        <Footer />
      </body>
    </html>
  )
}
