"use client"

import 'bootstrap/dist/css/bootstrap.css';

import './globals.css'
import Menubar from './components/Menubar';


import { Mulish  } from 'next/font/google'
import Footer from './components/Footer';
import Topbar from './components/Topbar';


const mulish = Mulish({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Topbar />
        <Menubar />
          {children}
        <Footer />
      </body>
    </html>
  )
}
